$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - "node_modules/**"
  - "public/locales/**"
  - "src/@types/**"
dictionaryDefinitions:
  - name: words
    path: ./src/config/cspell/words.txt
    description: custom dictionary
    addWords: true
dictionaries: ["words"]
language: "en, vi"
files:
  - "./src/**/*.{js,jsx,ts,tsx,json,md,mdx,html,css,scss,less}"
cache:
  cacheFormat: universal
  cacheStrategy: content
  useCache: true

languageSettings:
  - allowCompoundWords: false
    caseSensitive: false
    enabled: true
    languageId: "typescript"
  - allowCompoundWords: false
    caseSensitive: false
    enabled: true
    languageId: "typescriptreact"
  - allowCompoundWords: false
    caseSensitive: true
    enabled: true
    languageId: "json"
